env:
  global:
    CC_TEST_REPORTER_ID=CODE_CLIMATE_KEY
language: ruby
rvm:
  - 2.5.0
before_install:
  - bundle install
notifications: false
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec spec
  - bundle exec rubocop
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
